<a href="https://colab.research.google.com/github/kjedrzejczak/Machine_Learning_Bootcamp_practice/blob/main/01_preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import sklearn

print(np.__version__)
print(pd.__version__)
print(sklearn.__version__)

1.23.5
1.5.3
1.2.2


##Data

In [2]:
data = {'size' : ['Xl', 'L', 'M', 'L', 'M'],
        'color' : ['red', 'green', 'blue', 'green', 'red'],
        'gender': ['female', 'male', 'male', 'female', 'female'],
        'price': [199.0, 89.0, 99.0, 129.0, 79.0],
        'weight': [500, 450, 300, 300, 410],
        'bought': ['yes', 'no', 'yes', 'no', 'yes']}

df_raw = pd.DataFrame(data=data)
df_raw

size  color  gender  price  weight bought
0   Xl    red  female  199.0     500    yes
1    L  green    male   89.0     450     no
2    M   blue    male   99.0     300    yes
3    L  green  female  129.0     300     no
4    M    red  female   79.0     410    yes

In [3]:
df = df_raw.copy()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   size    5 non-null      object 
 1   color   5 non-null      object 
 2   gender  5 non-null      object 
 3   price   5 non-null      float64
 4   weight  5 non-null      int64  
 5   bought  5 non-null      object 
dtypes: float64(1), int64(1), object(4)
memory usage: 368.0+ bytes


In [4]:
for i in ['size', 'color', 'gender', 'bought']:
  df[i] = df[i].astype('category')

df.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype   
---  ------  --------------  -----   
 0   size    5 non-null      category
 1   color   5 non-null      category
 2   gender  5 non-null      category
 3   price   5 non-null      float64 
 4   weight  5 non-null      int64   
 5   bought  5 non-null      category
dtypes: category(4), float64(1), int64(1)
memory usage: 740.0 bytes


In [5]:
df.describe().T

count   mean        std    min    25%    50%    75%    max
price     5.0  119.0  48.476799   79.0   89.0   99.0  129.0  199.0
weight    5.0  392.0  89.833179  300.0  300.0  410.0  450.0  500.0

In [6]:
df.describe(include='category').T

count unique     top freq
size       5      3       L    2
color      5      3   green    2
gender     5      2  female    3
bought     5      2     yes    3

In [7]:
df

size  color  gender  price  weight bought
0   Xl    red  female  199.0     500    yes
1    L  green    male   89.0     450     no
2    M   blue    male   99.0     300    yes
3    L  green  female  129.0     300     no
4    M    red  female   79.0     410    yes

Label_encoding

In [8]:
from  sklearn.preprocessing import LabelEncoder

la = LabelEncoder()
la.fit(df['bought'])
la.transform(df['bought'])

array([1, 0, 1, 0, 1])

In [9]:
la.fit_transform(df['bought'])

array([1, 0, 1, 0, 1])

In [10]:
la.classes_

array(['no', 'yes'], dtype=object)

In [11]:
df['bought'] = la.fit_transform(df['bought'])

In [12]:
df

size  color  gender  price  weight  bought
0   Xl    red  female  199.0     500       1
1    L  green    male   89.0     450       0
2    M   blue    male   99.0     300       1
3    L  green  female  129.0     300       0
4    M    red  female   79.0     410       1

In [13]:
df['bought'] = la.inverse_transform(df['bought'])
df

size  color  gender  price  weight bought
0   Xl    red  female  199.0     500    yes
1    L  green    male   89.0     450     no
2    M   blue    male   99.0     300    yes
3    L  green  female  129.0     300     no
4    M    red  female   79.0     410    yes

In [14]:
from sklearn.preprocessing import  OneHotEncoder

encoder = OneHotEncoder(sparse=False)
encoder.fit(df[['size']])
encoder.transform(df[['size']])

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [15]:
encoder.categories_

[array(['L', 'M', 'Xl'], dtype=object)]

In [16]:
encoder = OneHotEncoder(drop='first', sparse=False)
encoder.fit(df[['size']])
encoder.transform(df[['size']])

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


array([[0., 1.],
       [0., 0.],
       [1., 0.],
       [0., 0.],
       [1., 0.]])

In [17]:
df

size  color  gender  price  weight bought
0   Xl    red  female  199.0     500    yes
1    L  green    male   89.0     450     no
2    M   blue    male   99.0     300    yes
3    L  green  female  129.0     300     no
4    M    red  female   79.0     410    yes

In [18]:
pd.get_dummies(data=df)

price  weight  size_L  size_M  size_Xl  color_blue  color_green  color_red  \
0  199.0     500       0       0        1           0            0          1   
1   89.0     450       1       0        0           0            1          0   
2   99.0     300       0       1        0           1            0          0   
3  129.0     300       1       0        0           0            1          0   
4   79.0     410       0       1        0           0            0          1   

   gender_female  gender_male  bought_no  bought_yes  
0              1            0          0           1  
1              0            1          1           0  
2              0            1          0           1  
3              1            0          1           0  
4              1            0          0           1

In [19]:
pd.get_dummies(data=df, drop_first=True)

price  weight  size_M  size_Xl  color_green  color_red  gender_male  \
0  199.0     500       0        1            0          1            0   
1   89.0     450       0        0            1          0            1   
2   99.0     300       1        0            0          0            1   
3  129.0     300       0        0            1          0            0   
4   79.0     410       1        0            0          1            0   

   bought_yes  
0           1  
1           0  
2           1  
3           0  
4           1

In [20]:
pd.get_dummies(data=df, drop_first=True, prefix='super')

price  weight  super_M  super_Xl  super_green  super_red  super_male  \
0  199.0     500        0         1            0          1           0   
1   89.0     450        0         0            1          0           1   
2   99.0     300        1         0            0          0           1   
3  129.0     300        0         0            1          0           0   
4   79.0     410        1         0            0          1           0   

   super_yes  
0          1  
1          0  
2          1  
3          0  
4          1

In [21]:
pd.get_dummies(data=df, drop_first=True, prefix_sep='*')

price  weight  size*M  size*Xl  color*green  color*red  gender*male  \
0  199.0     500       0        1            0          1            0   
1   89.0     450       0        0            1          0            1   
2   99.0     300       1        0            0          0            1   
3  129.0     300       0        0            1          0            0   
4   79.0     410       1        0            0          1            0   

   bought*yes  
0           1  
1           0  
2           1  
3           0  
4           1

In [22]:
pd.get_dummies(data=df, drop_first=True, columns=['size'])

color  gender  price  weight bought  size_M  size_Xl
0    red  female  199.0     500    yes       0        1
1  green    male   89.0     450     no       0        0
2   blue    male   99.0     300    yes       1        0
3  green  female  129.0     300     no       0        0
4    red  female   79.0     410    yes       1        0

In [23]:
df['price']


0    199.0
1     89.0
2     99.0
3    129.0
4     79.0
Name: price, dtype: float64

In [24]:
df['price'].mean()

119.0

In [26]:
round(df['price'].std(), 2)

48.48

In [28]:
def stantarizer(x):
  return (x - x.mean()) / x.std()

stantarizer(df['price'])

0    1.650274
1   -0.618853
2   -0.412568
3    0.206284
4   -0.825137
Name: price, dtype: float64

In [29]:
from sklearn.preprocessing import scale

scale(df['price'])

array([ 1.84506242, -0.69189841, -0.4612656 ,  0.2306328 , -0.92253121])

In [36]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaler.fit(df[['price']])
scaler.transform(df[['price']])


array([[ 1.84506242],
       [-0.69189841],
       [-0.4612656 ],
       [ 0.2306328 ],
       [-0.92253121]])

In [40]:
scaler = StandardScaler()
df[['price', 'weight']] = scaler.fit_transform(df[['price', 'weight']])
df

size  color  gender     price    weight bought
0   Xl    red  female  1.845062  1.344132    yes
1    L  green    male -0.691898  0.721849     no
2    M   blue    male -0.461266 -1.145002    yes
3    L  green  female  0.230633 -1.145002     no
4    M    red  female -0.922531  0.224022    yes

In [48]:
la = LabelEncoder()
df['bought'] = la.fit_transform(df['bought'])
df = pd.get_dummies(data=df, drop_first=True)
df

price    weight  bought  size_M  size_Xl  color_green  color_red  \
0  1.845062  1.344132       1       0        1            0          1   
1 -0.691898  0.721849       0       0        0            1          0   
2 -0.461266 -1.145002       1       1        0            0          0   
3  0.230633 -1.145002       0       0        0            1          0   
4 -0.922531  0.224022       1       1        0            0          1   

   gender_male  
0            0  
1            1  
2            1  
3            0  
4            0