<a href="https://colab.research.google.com/github/kjedrzejczak/Machine_Learning_Bootcamp_practice/blob/main/24_case_study_III.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sklearn

np.random.seed(42)
np.set_printoptions(precision=6, suppress=True, edgeitems=10, linewidth=1000, formatter=dict(float=lambda x: f'{c:.2f}'))


In [2]:
documents = ['Today is Friday',
            'I like Friday',
            'Today I am going to learn Python.',
            'Friday, Friday!!!']

print(documents)

['Today is Friday', 'I like Friday', 'Today I am going to learn Python.', 'Friday, Friday!!!']


In [3]:
from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer()
vectorizer.fit_transform(documents)

<4x9 sparse matrix of type '<class 'numpy.int64'>'
	with 12 stored elements in Compressed Sparse Row format>

In [4]:
vectorizer.fit_transform(documents).toarray()

array([[0, 1, 0, 1, 0, 0, 0, 0, 1],
       [0, 1, 0, 0, 0, 1, 0, 0, 0],
       [1, 0, 1, 0, 1, 0, 1, 1, 1],
       [0, 2, 0, 0, 0, 0, 0, 0, 0]])

In [5]:
vectorizer.get_feature_names_out()

array(['am', 'friday', 'going', 'is', 'learn', 'like', 'python', 'to', 'today'], dtype=object)

In [6]:
vectorizer.vocabulary_

{'today': 8,
 'is': 3,
 'friday': 1,
 'like': 5,
 'am': 0,
 'going': 2,
 'to': 7,
 'learn': 4,
 'python': 6}

In [7]:
vectorizer.fixed_vocabulary_

False

In [8]:
df =pd.DataFrame(data=vectorizer.fit_transform(documents).toarray(), columns=vectorizer.get_feature_names_out())
df

am  friday  going  is  learn  like  python  to  today
0   0       1      0   1      0     0       0   0      1
1   0       1      0   0      0     1       0   0      0
2   1       0      1   0      1     0       1   1      1
3   0       2      0   0      0     0       0   0      0

In [9]:
vectorizer.transform(['Friday morning']).toarray()  # dopasowanie tylko do tego co było wcześniej

array([[0, 1, 0, 0, 0, 0, 0, 0, 0]])

# Bigram

In [10]:
bigram = CountVectorizer(ngram_range=(1, 2), min_df=1)
bigram.fit_transform(documents).toarray()

array([[0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0],
       [1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0],
       [0, 0, 2, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [11]:
bigram.vocabulary_

{'today': 15,
 'is': 6,
 'friday': 2,
 'today is': 17,
 'is friday': 7,
 'like': 10,
 'like friday': 11,
 'am': 0,
 'going': 4,
 'to': 13,
 'learn': 8,
 'python': 12,
 'today am': 16,
 'am going': 1,
 'going to': 5,
 'to learn': 14,
 'learn python': 9,
 'friday friday': 3}